### ISSUE TITLE
คิดหัวข้อโปรเจค 

### ISSUE THREAD

**Issue by quartins** [quartins/comprog_project#1]
รวบรวมหัวข้อที่สมาชิกในกลุ่มมีความสนใจ 
1.โปรแกรมดูดวง
2.chatbot (คุยเกี่ยวกับความรู้สึก ระบายอารมณ์)
3.Bingo
4.ระบบหาหอพักหลังมช.
5.สลิปร้านอาหาร/ร้านค้า
6.ระบบจองที่พัก/ตั๋ว

**Comment by quartins** [comment]
โปรแกรมดูดวง +1

**Comment by EileenIL** [comment]
โปรแกรมดูดวง +2

**Comment by kiejibi** [comment]
โปรแกรมดูดวง+2

**Comment by EileenIL** [comment]
ระบบหาหอพัก +1

**Comment by xtxme** [comment]
โปรแกรมดูดวง+3

**Comment by jjjaoant** [comment]
สลิปร้านอาหาร +1

**Comment by PraeThipwarin** [comment]
หาหอพัก +2
