### ISSUE TITLE
design

### ISSUE THREAD

**Issue by quartins** [quartins/comprog_project#5]
ทำไพ่และออกแบบ

**Comment by quartins** [comment]
ทำงานใน [canva](https://www.canva.com/design/DAF8Xabr004/c3E1Ee9E7wMFwjmxa5N0qg/edit?utm_content=DAF8Xabr004&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by jjjaoant** [comment]
หน้าดราฟตรงเเสดงผลคร่าวๆ 
[Project Compro .pdf](https://github.com/quartins/comprog_project/files/14332436/Project.Compro.pdf)
